apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ''
  labels:
    appgroup: ''
    version: v1
  name: hello-world
  namespace: devops
spec:
  selector:
    matchLabels:
      app: hello-world
      version: v1
  template:
    metadata:
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
      labels:
        app: hello-world
        version: v1
    spec:
      containers:
        - image: 'swr.cn-north-4.myhuaweicloud.com/test-liuxinzhang/hello-world:v1.1'
          name: container-1
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 512Mi
          env:
            - name: PAAS_APP_NAME
              value: hello-world
            - name: PAAS_NAMESPACE
              value: devops
            - name: PAAS_PROJECT_ID
              value: 0b11dbdef68025bf2f9ec00948842a9f
            - name: SPRING_PROFILES_ACTIVE
              value: test
          volumeMounts: []
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers: []
        options:
          - name: timeout
            value: ''
          - name: ndots
            value: '5'
          - name: single-request-reopen
        searches: []
      affinity: {}
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
  replicas: 1
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
  namespace: devops
  annotations: {}
spec:
  selector:
    app: hello-world
  externalTrafficPolicy: Cluster
  ports:
    - name: cce-service-0
      targetPort: 8080
      nodePort: 0
      port: 8080
      protocol: TCP
  type: NodePort